### ISSUE TITLE
请修改下包名或者vendor的配置

### ISSUE THREAD

**Issue by linkerlin** [picone/SearchEngine#1]
go build
main.go:4:2: cannot find package "ChienHo/SearchEngine/controllers"

**Comment by linkerlin** [comment]
当我建立一些软连接绕过上面的问题后，又遇到了新问题：
go build
# github.com/picone/SearchEngine
./main.go:18:50: cannot use middlewares.GetPagination() (type "ChienHo/SearchEngine/vendor/github.com/gin-gonic/gin".HandlerFunc) as type "github.com/picone/SearchEngine/vendor/github.com/gin-gonic/gin".HandlerFunc in argument to r.RouterGroup.GET
./main.go:18:50: cannot use controllers.Search (type func(*"ChienHo/SearchEngine/vendor/github.com/gin-gonic/gin".Context)) as type "github.com/picone/SearchEngine/vendor/github.com/gin-gonic/gin".HandlerFunc in argument to r.RouterGroup.GET
./main.go:19:8: cannot use controllers.SearchDetail (type func(*"ChienHo/SearchEngine/vendor/github.com/gin-gonic/gin".Context)) as type "github.com/picone/SearchEngine/vendor/github.com/gin-gonic/gin".HandlerFunc in argument to r.RouterGroup.GET

**Comment by linkerlin** [comment]
我又加了一个软连接
vendor]$ ln -s ../../ ChienHo

**Comment by linkerlin** [comment]
`go build
# github.com/picone/SearchEngine/vendor/ChienHo/SearchEngine/vendor/ChienHo/SearchEngine/documents
vendor/ChienHo/SearchEngine/vendor/ChienHo/SearchEngine/documents/indexing.go:27:21: cannot use mongo.MongoDatabase.C("indexing") (type *"github.com/picone/SearchEngine/vendor/ChienHo/SearchEngine/vendor/ChienHo/SearchEngine/vendor/ChienHo/SearchEngine/vendor/gopkg.in/mgo.v2".Collection) as type *"github.com/picone/SearchEngine/vendor/ChienHo/SearchEngine/vendor/ChienHo/SearchEngine/vendor/gopkg.in/mgo.v2".Collection in assignment
vendor/ChienHo/SearchEngine/vendor/ChienHo/SearchEngine/documents/indexing.go:60:66: cannot use segment.GetSegmenter().Segment(([]byte)(keyword)) (type []"github.com/picone/SearchEngine/vendor/ChienHo/SearchEngine/vendor/ChienHo/SearchEngine/vendor/ChienHo/SearchEngine/vendor/github.com/huichen/sego".Segment) as type []"github.com/picone/SearchEngine/vendor/ChienHo/SearchEngine/vendor/ChienHo/SearchEngine/vendor/github.com/huichen/sego".Segment in argument to "github.com/picone/SearchEngine/vendor/ChienHo/SearchEngine/vendor/ChienHo/SearchEngine/vendor/github.com/huichen/sego".SegmentsToSlice
vendor/ChienHo/SearchEngine/vendor/ChienHo/SearchEngine/documents/pages.go:25:17: cannot use mongo.MongoDatabase.C("pages") (type *"github.com/picone/SearchEngine/vendor/ChienHo/SearchEngine/vendor/ChienHo/SearchEngine/vendor/ChienHo/SearchEngine/vendor/gopkg.in/mgo.v2".Collection) as type *"github.com/picone/SearchEngine/vendor/ChienHo/SearchEngine/vendor/ChienHo/SearchEngine/vendor/gopkg.in/mgo.v2".Collection in assignment`

**Comment by linkerlin** [comment]
简单来说，ChienHo这个目录并不存在

**Comment by picone** [comment]
想不到自己做的玩意还有人用，现在跑还是会崩溃，锁的等待时间太长还需要优化。
希望有什么意见可以提出来一起探讨

**Comment by linkerlin** [comment]
@picone 别用锁了，用chan + goroutine 吧。
不要共享那么多数据结构，用一个goroutine管理共享数据结构，其他的goroutine发 func() 到 chan里面。
那个admin goroutine执行之。

**Comment by linkerlin** [comment]
go build
# github.com/picone/SearchEngine/documents
documents/indexing.go:9:2: imported and not used: "log"
我提交了一个PR #2
